spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: admin
    password: 2222

  jpa:
    hibernate:
      ddl-auto: none

  sql:
    init:
      mode: always

logging:
  level:
    ROOT: ERROR